import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	Container: {
		flex: 1,
		backgroundColor: '#fff',
	},
	ScrollContainer: {
		padding: 10,
	},
	AvatarContainer: {
		flexDirection: 'row',
		width: '100%',
		height: 95,
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 10,
	},
	UserAvatar: {
		backgroundColor: '#f15c2b',
		width: 95,
		height: 95,
		borderRadius: 100,
		elevation: 10,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 5,
		},
		shadowOpacity: 0.34,
		shadowRadius: 6.27,
		alignItems: 'center',
		justifyContent: 'center',
		position: 'relative',
	},
	UserPic: {
		height: '90%',
		width: '90%',
		borderRadius: 100,
	},
	PicOverlay: {
		position: 'absolute',
		height: '90%',
		width: '90%',
		backgroundColor: '#0000003f',
		borderRadius: 100,
		margin: 'auto',
		alignItems: 'center',
		justifyContent: 'center',
	},
	HeadingRow: {
		flexDirection: 'row',
		alignItems: 'center',
		height: 50,
	},
	HeadingText: {
		fontSize: 24,
		fontWeight: 'bold',
	},
	EditButton: {
		marginLeft: 'auto',
		height: 40,
		width: 40,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 120,
	},
	DeleteButton: {
		width: '100%',
		flexDirection: 'row',
		elevation: 1,
		backgroundColor: '#D73A49',
		height: 45,
		borderRadius: 8,
		alignItems: 'center',
		paddingHorizontal: 12,
		marginTop: 10,
	},
	DeleteButtonText: {
		color: '#fff',
		fontSize: 18,
		marginLeft: 'auto',
		marginRight: 'auto',
	},
	PickerContainer: {
		flexDirection: 'column',
		borderRadius: 8,
		borderColor: '#fb8c00',
		borderWidth: 2,
		padding: 10,
		paddingVertical: 5,
		backgroundColor: '#fff',
		elevation: 1,
		marginBottom: 10,
		height: 50,
	},
	Picker: {
		height: '100%',
		borderWidth: 1,
		borderColor: '#000',
		marginTop: -8,
		marginLeft: -7,
	},
	InputLabel: {
		fontWeight: 'bold',
		fontSize: 12,
	},
	PicActionsContainer: {
		flexDirection: 'column',
		width: '45%',
		marginLeft: 'auto',
	},
	PicButton: {
		width: '75%',
		borderRadius: 8,
		flexDirection: 'row',
		justifyContent: 'space-evenly',
		alignItems: 'center',
		marginBottom: 8,
		elevation: 1,
	},
	PicButtonDisabled: {
		backgroundColor: '#e5e5e5',
	},
	PicButtonText: {
		color: '#fff',
	},
	EditPicButton: {
		backgroundColor: '#38C2FF',
	},
	DeletePicButton: {
		backgroundColor: '#d73a49',
	},
	UploadButton: {
		width: 45,
		height: 45,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 100,
		backgroundColor: '#fb8c00',
		marginLeft: 10,
		elevation: 5,
	},
});
