import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	PageTwo: {
		flex: 1,
		justifyContent: 'space-evenly',
		alignItems: 'center',
		position: 'relative',
		paddingTop: 5,
		paddingHorizontal: 20,
		paddingBottom: 35,
	},
	NextSectionButton: {
		position: 'absolute',
		bottom: 5,
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		height: 45,
		marginTop: 10,
	},
	PreviousSectionButton: {
		position: 'absolute',
		top: 5,
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		height: 45,
		marginBottom: 5,
	},
	FormGroup: {
		flexDirection: 'row',
		alignItems: 'center',
		width: '90%',
		borderRadius: 8,
		borderBottomWidth: 1,
		borderBottomColor: '#EAEAEA',
		height: 50,
		padding: 5,
		paddingBottom: -6,
		marginTop: 5,
		marginBottom: 5,
	},
	SectionTitle: {
		textAlign: 'center',
		fontSize: 24,
		fontWeight: 'bold',
	},
	HelpText: {
		textAlign: 'center',
		fontSize: 16,
		marginHorizontal: 30,
	},
	Picker: {
		height: 54,
		width: '100%',
		padding: 0,
		margin: 0,
		borderWidth: 1,
		borderColor: '#000',
	},
	PriceContainer: {
		flexDirection: 'column',
		height: '100%',
		paddingHorizontal: 5,
		justifyContent: 'space-between',
		width: '50%',
	},
	PriceRow: {
		flexDirection: 'row',
		flex: 1,
		marginTop: 'auto',
		width: '100%',
	},
	PriceInput: {
		height: 35,
		width: '60%',
		marginLeft: 'auto',
		marginRight: 18,
		marginTop: 5,
		textAlign: 'right',
		borderBottomColor: '#e5e5e5',
		borderBottomWidth: 1,
	},
	PriceCurrency: {
		height: 35,
		width: '10%',
		marginTop: 15,
	},
	StatusRow: {
		flexDirection: 'row',
		height: 54,
	},
	StatusContainer: {
		flexDirection: 'column',
		width: '50%',
		height: '100%',
	},
	fullFlex: {
		flex: 1,
	},
});
