import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	Input: {
		marginLeft: 5,
		padding: 6,
		flexGrow: 100,
		fontSize: 15,
		fontFamily: 'Roboto',
	},
	FormGroup: {
		flexDirection: 'row',
		alignItems: 'center',
		width: '85%',
		borderRadius: 8,
		borderBottomWidth: 1,
		borderBottomColor: '#EAEAEA',
		height: 54,
		padding: 6,
		paddingBottom: -6,
		marginTop: 8,
		marginBottom: 8,
	},
	InputError: {
		borderBottomColor: 'red',
	},
	RegisterButton: {
		width: 140,
		padding: 10,
		elevation: 1,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 1,
		},
		shadowOpacity: 0.18,
		shadowRadius: 1.0,
		marginTop: 30,
		marginBottom: 30,
		borderRadius: 8,
		backgroundColor: '#EB6339',
		alignItems: 'center',
	},
	RegisterText: {
		fontSize: 20,
		color: '#FFFFFF',
	},
	TextH1: {
		fontSize: 24,
		color: '#000',
		fontWeight: '700',
	},
	TextP: {
		fontSize: 16,
		textAlign: 'center',
		color: '#000',
	},
	ModalButton: {
		width: '60%',
		padding: 10,
		elevation: 5,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 3.84,
		borderRadius: 50,
		backgroundColor: '#3eb3e5',
		alignItems: 'center',
	},
	ModalButtonError: {
		height: 45,
		paddingVertical: 5,
	},
	ButtonText: {
		fontSize: 28,
		textAlign: 'center',
		color: '#FFFFFF',
	},
	AvatarHolder: {
		width: '100%',
		height: '100%',
		borderRadius: 100,
		alignItems: 'center',
		justifyContent: 'center',
	},
	AvatarImage: {
		width: '100%',
		height: '100%',
		borderRadius: 100,
		opacity: 0.6,
	},
	CameraIcon: {
		height: 40,
		width: 40,
	},
	HeaderClickable: {
		width: '100%',
		height: '100%',
		borderRadius: 100,
		position: 'relative',
		alignItems: 'center',
		justifyContent: 'center',
	},
	ContentContainerStyle: {
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	FAEdit: {
		position: 'absolute',
		alignSelf: 'center',
	},
	LocationButton: {
		position: 'absolute',
		top: -80,
		right: 20,
		borderRadius: 100,
		width: 45,
		height: 45,
		elevation: 2,
		backgroundColor: '#fff',
		alignItems: 'center',
		justifyContent: 'center',
	},
	BottomSheet: {
		elevation: 1,
		backgroundColor: 'white',
		padding: 16,
		height: '100%',
	},
	BottomSheetTracker: {
		width: 45,
		height: 4,
		backgroundColor: '#e5e5e5',
		borderRadius: 12,
		marginLeft: 'auto',
		marginRight: 'auto',
	},
	SheetHeader: {
		marginVertical: 15,
	},
	SheetHeaderText: {
		width: '100%',
		textAlign: 'center',
	},
});
