import { StyleSheet } from 'react-native';

export default (Styles = StyleSheet.create({
    TextCenter: { textAlign: 'center' },
    CardScrollView: {
        backgroundColor: '#F9F9F9',
        borderRadius: 8,
        flex: 1,
    },
    CardContainer: {
        alignItems: 'center',
        minHeight: '300%',
        height: '300%',
        maxHeight: '300%',
    },
    PageOne: {
        height: '33.3333%',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        position: 'relative',
        paddingVertical: 30,
        padding: 20,
    },
    PageTwo: {
        height: '33.3333%',
        width: '100%',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        position: 'relative',
        paddingVertical: 30,
        padding: 20,
    },
    PageThree: {
        minHeight: 480,
        height: '33.3333%',
        width: '100%',
        position: 'relative',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        paddingVertical: 30,
        padding: 20,
    },
    HeadingText: {
        color: '#000000',
        fontWeight: '600',
        fontSize: 24,
    },
    CoverContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        height: '100%',
    },
    Cover: {
        width: 140,
        height: '100%',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#000000',
        marginHorizontal: 5,
    },
    BackCover: {
        width: 140,
        height: 220,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#000000',
        marginHorizontal: 5,
    },
    ImageHolder: {
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: '#000000',
        backgroundColor: '#F1F1F1',
    },
    NextSectionButton: {
        position: 'absolute',
        bottom: 5,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        height: 45,
        marginTop: 10,
    },
    PreviousSectionButton: {
        position: 'absolute',
        top: 5,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        height: 45,
        marginBottom: 5,
    },
    FormGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '90%',
        borderRadius: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#EAEAEA',
        height: 50,
        padding: 5,
        paddingBottom: -6,
        marginTop: 5,
        marginBottom: 5,
    },
    FormGroupRow: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '50%',
        borderRadius: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#EAEAEA',
        height: 50,
        padding: 5,
        paddingBottom: -6,
        marginTop: 5,
        marginBottom: 5,
    },
    Row: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-around',
    },
    FormGroupColumn: {
        flexDirection: 'column',
        alignItems: 'center',
        height: 54,
        padding: 5,
        marginTop: 8,
        marginBottom: 8,
    },
    PostBookButton: {
        width: 120,
        height: 45,
        backgroundColor: '#ff8c00',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.18,
        shadowRadius: 1.0,
        borderRadius: 10,
    },
    PostBookText: {
        fontSize: 20,
        color: '#FFFFFF',
    },
    TextH1: {
        fontSize: 24,
        color: '#000',
        fontWeight: '700',
    },
    TextP: {
        fontSize: 16,
        textAlign: 'center',
        color: '#000',
    },
    ModalButton: {
        width: '60%',
        padding: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        borderRadius: 50,
        backgroundColor: '#3eb3e5',
        alignItems: 'center',
    },
    ButtonText: {
        fontSize: 28,
        textAlign: 'center',
        color: '#FFFFFF',
    },
}));
